import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MainPage from './mainpage'

export default function Home() {
  return (
    <>
      <Head>
        <title>uzair Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage/>

      </>
  )
}
